<?xml version="1.0" encoding="UTF-8"?>
<!-- input-inlineDTD.xml (Document Type Definition) -->
<!DOCTYPE Input [
	<!ELEMENT Input (UserData,FileLocation)>
		<!ELEMENT UserData 				(RequiredStockSymbols,RequiredParameters,QueryType)>
			<!ELEMENT RequiredStockSymbols 		(#PCDATA) > 
			<!ELEMENT RequiredParameters 	(#PCDATA) >
			<!ELEMENT QueryType 			(#PCDATA) >
		<!ELEMENT FileLocation 			(TempFile,OutputFile)>
			<!ELEMENT TempFile	 			(#PCDATA) >
			<!ELEMENT OutputFile 			(#PCDATA) >
]>
<Input>
<UserData>
	<RequiredStockSymbols>GOOG,AAPL</RequiredStockSymbols> <!-- ,AAPL,AMZN,BIDU,MA,NFLX</RequiredStockSymbols> -->
	<!-- <RequiredParameters>Day's Range,52wk Range,Prev Close,Open,Div &amp; Yield,P/E (ttm),EPS (ttm),Beta,1y Target Est</RequiredParameters> -->
	<RequiredParameters>Ask,AverageVolume</RequiredParameters> <!-- obtained from the 'ParamList' classes eg. ParamAsk.getparamName() -->
	<QueryType>api</QueryType> <!-- api/historical/WEBYAHOO -->
</UserData>
<FileLocation>
	<TempFile>tempFile.html</TempFile>
	<OutputFile>outputDir/stockData.csv</OutputFile>
</FileLocation>


</Input>

